- name: Install packages (not for RedHat distros)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ pkg_list }}"
  when: ansible_os_family != 'RedHat'

- name: Install packages using yum (for RedHat distros)
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: "{{ extra_os_repos }}"
  with_items:
    - "{{ pkg_list }}"
  when: ansible_os_family == 'RedHat'
